# Generated by Django 5.2.15 on 2026-07-06
# NOTE: This migration was trimmed to ONLY add the two new School fields
# (designated_teacher_name / designated_teacher_mobile). The auto-generated
# CreateModel (LearningVideo/VideoProgress) and choices AlterField ops were
# intentionally removed so this deploy is purely additive and does not touch
# pre-existing tables on the server.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_ideasubmission_competition_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='designated_teacher_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='school',
            name='designated_teacher_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
