# Generated by Django 5.2.16 on 2026-07-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_add_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField()),
                ('youtube_id', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='ai_suggested_category',
            field=models.CharField(blank=True, choices=[('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health', 'Good Health and Well-Being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water', 'Clean Water and Sanitation'), ('clean-energy', 'Affordable and Clean Energy'), ('economic-growth', 'Decent Work and Economic Growth'), ('industry-innovation', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities', 'Sustainable Cities and Communities'), ('responsible-consumption', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-justice', 'Peace, Justice and Strong Institutions'), ('partnerships', 'Partnerships for the Goals'), ('edtech', 'EdTech'), ('sustainability', 'Sustainability'), ('health', 'Health & Wellness'), ('fintech', 'FinTech'), ('social_impact', 'Social Impact'), ('agriculture', 'Agriculture'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('other', 'Other'), ('incoherent', 'Incoherent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='competition_track',
            field=models.CharField(blank=True, choices=[('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health', 'Good Health and Well-Being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water', 'Clean Water and Sanitation'), ('clean-energy', 'Affordable and Clean Energy'), ('economic-growth', 'Decent Work and Economic Growth'), ('industry-innovation', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities', 'Sustainable Cities and Communities'), ('responsible-consumption', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-justice', 'Peace, Justice and Strong Institutions'), ('partnerships', 'Partnerships for the Goals')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='final_category',
            field=models.CharField(blank=True, choices=[('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health', 'Good Health and Well-Being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water', 'Clean Water and Sanitation'), ('clean-energy', 'Affordable and Clean Energy'), ('economic-growth', 'Decent Work and Economic Growth'), ('industry-innovation', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities', 'Sustainable Cities and Communities'), ('responsible-consumption', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-justice', 'Peace, Justice and Strong Institutions'), ('partnerships', 'Partnerships for the Goals'), ('edtech', 'EdTech'), ('sustainability', 'Sustainability'), ('health', 'Health & Wellness'), ('fintech', 'FinTech'), ('social_impact', 'Social Impact'), ('agriculture', 'Agriculture'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('other', 'Other'), ('incoherent', 'Incoherent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='track',
            field=models.CharField(blank=True, choices=[('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health', 'Good Health and Well-Being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water', 'Clean Water and Sanitation'), ('clean-energy', 'Affordable and Clean Energy'), ('economic-growth', 'Decent Work and Economic Growth'), ('industry-innovation', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities', 'Sustainable Cities and Communities'), ('responsible-consumption', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-justice', 'Peace, Justice and Strong Institutions'), ('partnerships', 'Partnerships for the Goals')], max_length=30),
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='students.student')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='students.learningvideo')),
            ],
            options={
                'unique_together': {('student', 'video')},
            },
        ),
    ]
