# Generated by Django 5.2.15 on 2026-07-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_ideabookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
