# Generated by Django 5.2.16 on 2026-08-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Google Places place_id — source of truth to prevent duplicate school registrations.', max_length=255, null=True, unique=True),
        ),
    ]
