# Generated by Django 5.2.16 on 2026-07-21 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_content_event_fields'),
        ('students', '0018_student_is_paid_student_payment_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatorassignment',
            name='score',
            field=models.IntegerField(blank=True, help_text='Manual evaluation score (0-100)', null=True),
        ),
        migrations.CreateModel(
            name='CertificateIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('participation', 'Participation (Idea Submission)'), ('top100', 'Top 100'), ('top400', 'Top 400'), ('school_champion', 'School Champion')], max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('name_used', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('is_test', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='students.school')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_sent', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cert_type', 'status'], name='admins_cert_cert_ty_f859ad_idx'), models.Index(fields=['student', 'cert_type'], name='admins_cert_student_0c3ca9_idx')],
            },
        ),
    ]
