# Generated by Django 5.2.16 on 2026-08-01 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_alter_evaluatorassignment_score_certificateissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('whatsapp_template', 'WhatsApp Template'), ('flyer', 'Flyer'), ('brochure', 'Brochure'), ('standee', 'Standee'), ('banner', 'Banner'), ('bmc', 'Business Model Canvas (BMC)'), ('pitch_template', 'Pitch Template'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('file', models.FileField(upload_to='digital_resources/%Y/%m/')),
                ('visibility', models.CharField(choices=[('all', 'Students & Schools'), ('students', 'Students Only'), ('schools', 'Schools Only')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
