# Generated by Django 5.2.15 on 2026-07-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_juryprofile_additional_notes_juryprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='announcements_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
